### PR TITLE
add attraction type, and can use multiple languages

### PR DESCRIPTION
**Pull request by eltorio**
Dear Algo7,
For my own use I needed to scrap an attraction in multiple languages, this is my modifications.
as the variable "LANGUAGES" is not mandatory and languages defaulted to ["en"] it is compatible with your old behavior with "en" hard coded.
Ronan

### CODE REVIEW

**Comment by eltorio** [comment]
I also add an optional json with variable `FILETYPE=json` output which contains all information needed to produce a card similar to original one like url, photos, username…

**Comment by algo7** [comment]
> I also add an optional json with variable `FILETYPE=json` output which contains all information needed to produce a card similar to original one like url, photos, username…

Hi there, thanks for the PR. I'm on vacation right now. I'll have a derailed look next Monday.

**Comment by eltorio** [comment]
Thank you for reviewing my pull request!  

I hope my recent commits won’t pollute the PR

I’ve made several modifications to utilize your work as a replacement for my old reviewer proxy, using Puppeteer instead of a direct GraphQL query.  
Additionally, I’ve added a GraphQL endpoint to query results from a Vue application, specifically targeting a specific JSON schema output.
However, there’s still some work to be done. I’m currently working on implementing a routine for refreshing records and adding new ones. Your feedback and suggestions are greatly appreciated!

**Comment by algo7** [comment]
Hi [Contributor's Name],

Thank you for your contribution to the TripAdvisor Review Scraper project. Your efforts to enhance its functionality are truly appreciated.

I've taken a closer look at the changes proposed in pull request #185, particularly the addition of a GraphQL server. While the initiative to introduce new features is commendable, I'd like to share some considerations that are crucial for the project's direction and integration requirements.

The `scraper` is designed to operate as a command-line utility, executing tasks efficiently before terminating. This design ensures simplicity and ease of use, catering to users who prefer straightforward, single-run tools. The introduction of a GraphQL server shifts the application towards becoming a long-running service or daemon. While innovative, this change could complicate the tool's operation and diverge from its original purpose.

Moreover, it's important to consider the integration with the `container_provisioner` module located in our project repository. This module is designed to work seamlessly with the scraper, expecting it to be a lightweight, non-daemonized utility. The proposed changes might pose challenges to this integration, affecting the overall functionality and user experience.

Could we explore a way to incorporate your valuable improvements while maintaining the scraper's utility nature? Perhaps we could discuss alternative approaches that enhance functionality without transforming it into a long-running service. This way, we can preserve the ease of use and integration compatibility, which are key aspects of the project.

I look forward to your thoughts and am open to any suggestions you might have. Let's work together to find the best solution that aligns with the project's goals and user expectations.

Best regards,

Algo7

**Comment by briacl** [comment]
Hi Algo7 I didn't want to add the GraphQL but since I made the PR from my main branch it continues to populate the PR automatically the PR must be limited to fcde2e47a3 which concerns multi language and full json output

**Comment by algo7** [comment]
> Hi Algo7 I didn't want to add the GraphQL but since I made the PR from my main branch it continues to populate the PR automatically the PR must be limited to fcde2e47a3 which concerns multi language and full json output

Hi @briacl ,

In that case is it possible for you to cherry pic and open another PR?

**Pull request closed without merging**
